# Generated by Django 2.1 on 2019-08-25 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='logo/%Y')),
                ('name', models.CharField(blank=True, default='星之羽网络科技有限公司', max_length=36, verbose_name='企业名称')),
                ('introduce', models.TextField(blank=True, default='', max_length=360, verbose_name='企业描述')),
                ('address', models.CharField(blank=True, default='', max_length=72, verbose_name='企业地址')),
                ('mobile', models.CharField(blank=True, default='', max_length=12, verbose_name='企业电话')),
                ('qq', models.CharField(blank=True, default='', max_length=12, verbose_name='企业QQ')),
                ('email', models.EmailField(blank=True, default='admin@admin.admin', max_length=254, verbose_name='企业邮箱')),
                ('icp', models.CharField(blank=True, default='', max_length=100, verbose_name='企业备案号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否使用')),
            ],
            options={
                'verbose_name': '企业信息',
                'verbose_name_plural': '企业信息',
            },
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
