# Generated by Django 2.1 on 2019-08-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_auto_20190825_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
    ]
