# Generated by Django 2.1 on 2019-05-18 20:15

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('goods_detail', models.CharField(max_length=200, verbose_name='商品描述')),
                ('goods_introduce', tinymce.models.HTMLField(verbose_name='商品介绍页')),
                ('goods_pic', models.ImageField(blank=True, upload_to='goods/%Y/%m', verbose_name='商品图片')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品价格')),
                ('goods_click', models.IntegerField(default=0, verbose_name='商品人气')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='商品添加时间')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30, verbose_name='类型名称')),
                ('type_imamge', models.ImageField(blank=True, upload_to='goodstype/%Y/%m', verbose_name='类型图片')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '商品类型',
                'verbose_name_plural': '商品类型',
            },
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='goods_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsType', verbose_name='商品类型'),
        ),
    ]
