# Generated by Django 2.1 on 2019-05-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='goods_degree',
            field=models.CharField(choices=[('9', '9成'), ('8', '前端'), ('7', '日记'), ('6', 'Linux'), ('5', '5成以下')], default=1, max_length=16, verbose_name='商品新旧程度'),
            preserve_default=False,
        ),
    ]
