# Generated by Django 2.1 on 2019-07-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0002_auto_20190526_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='首页推荐'),
        ),
    ]
