# Generated by Django 2.1 on 2019-07-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0003_goodsinfo_is_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='goods_old_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='商品原价(￥)'),
        ),
    ]
