# Generated by Django 2.1 on 2019-08-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0005_goodcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodcomment',
            name='content',
            field=models.TextField(verbose_name='评论内容'),
        ),
    ]
