# Generated by Django 2.1 on 2019-08-12 14:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0006_auto_20190809_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_introduce',
            field=tinymce.models.HTMLField(default='\n该商品详细信息\u200b\n\n卖家姓名：XXX\n\n卖家所在宿舍：XXX\n\n卖家联系方式：\n\n    QQ：\n\n    微信：\n\n    手机号：\n\n    \n    \n    \n    ', verbose_name='商品介绍页'),
        ),
    ]
