# Generated by Django 2.1 on 2019-08-12 15:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0007_auto_20190812_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_introduce',
            field=tinymce.models.HTMLField(default='\n<h1>卖家姓名：XXX</h1>\n\n<h1>卖家所在宿舍：XXX</h1>\n\n<h1>卖家联系方式：</h1>\n\n    <h1>QQ：</h1>\n\n    <h1>微信：</h1>\n\n    <h1>手机号：</h1>\n\n    \n    \n    \n    ', verbose_name='商品介绍页'),
        ),
    ]
