# Generated by Django 2.1 on 2019-05-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=30, verbose_name='学院名')),
            ],
            options={
                'verbose_name': '学院',
                'verbose_name_plural': '学院',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sno', models.CharField(max_length=20, verbose_name='学号')),
                ('user_name', models.CharField(blank=True, default='张三', max_length=30, null=True, verbose_name='姓名')),
                ('user_pwd', models.CharField(max_length=30, verbose_name='密码')),
                ('user_mobile', models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='手机')),
                ('user_mail', models.CharField(max_length=30, verbose_name='邮箱')),
                ('user_address', models.CharField(default='', max_length=100, verbose_name='地址')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='用户添加时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
