# Generated by Django 2.1 on 2019-05-18 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='df_user.College', verbose_name='学院'),
            preserve_default=False,
        ),
    ]
