# Generated by Django 2.1 on 2019-05-11 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0002_auto_20190511_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_mobile',
            field=models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_college',
            field=models.ForeignKey(default='信息传媒', on_delete=django.db.models.deletion.CASCADE, to='df_user.College', verbose_name='学院'),
        ),
    ]
