# Generated by Django 2.1 on 2019-05-18 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0003_auto_20190518_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.College', verbose_name='学院'),
        ),
    ]
