# Generated by Django 2.1 on 2019-05-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0003_auto_20190511_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_address',
            field=models.CharField(default='', max_length=100, verbose_name='地址'),
        ),
    ]
