# Generated by Django 2.1 on 2019-08-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0008_auto_20190812_1502'),
        ('df_user', '0005_auto_20190813_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_fav',
            field=models.ManyToManyField(to='df_goods.GoodsInfo', verbose_name='用户收藏'),
        ),
    ]
