# Generated by Django 2.1 on 2019-05-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0005_auto_20190518_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_address',
            field=models.CharField(max_length=100, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='手机'),
        ),
    ]
