# Generated by Django 2.1 on 2019-08-22 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0008_auto_20190812_1502'),
        ('df_user', '0006_userprofile_user_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_fav',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_fav',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo', verbose_name='用户收藏'),
            preserve_default=False,
        ),
    ]
