# Generated by Django 2.1 on 2019-08-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0007_auto_20190822_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_fav',
        ),
    ]
