# Generated by Django 2.1 on 2019-08-25 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0008_remove_userprofile_user_fav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dormitory_num', models.CharField(max_length=30, verbose_name='宿舍号')),
            ],
            options={
                'verbose_name': '宿舍号',
                'verbose_name_plural': '宿舍号',
            },
        ),
        migrations.CreateModel(
            name='DormitoryBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dormitory_building_name', models.CharField(max_length=30, verbose_name='宿舍楼')),
            ],
            options={
                'verbose_name': '宿舍楼',
                'verbose_name_plural': '宿舍楼',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_dormitory_building_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='df_user.DormitoryBuilding', verbose_name='宿舍楼'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_dormitory_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='df_user.Dormitory', verbose_name='宿舍号'),
        ),
    ]
