# Generated by Django 2.1 on 2019-08-25 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0009_auto_20190825_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_dormitory_building_name',
            new_name='user_dormitory_building',
        ),
    ]
