# Generated by Django 2.1 on 2019-08-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0010_auto_20190825_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_remark',
            field=models.CharField(default=1, max_length=30, verbose_name='备注'),
            preserve_default=False,
        ),
    ]
